### ISSUE TITLE
every photo detail page makes S3 HEAD request

### ISSUE THREAD

**Issue by arahayrabedian** [agile-leaf/50mm#11]
My growing understanding of 50mm is still limited, but i think [this blob for ImageExists]( https://github.com/agile-leaf/50mm/blob/master/album.go#L256-L272) can be significantly improved to not  require a (blocking (and paid albeit in very small amounts)) request to S3 to confirm existence of a photo.

I'm not sure why it's even required since the album indices should be up to date enough via caching for an inconsistent situation not to last very long.

**Comment by arahayrabedian** [comment]
I just realised this should be a trivial fix once #14 makes it in

**Comment by theonejb** [comment]
If this is solved by your latest pull request, please mark as closed.

**Comment by arahayrabedian** [comment]
it's solved by the one i just opened ( #15 , not #14 ), one needed the other

**Comment by arahayrabedian** [comment]
haha you're going to murder me, but that's the only other work i've done :)

**Comment by theonejb** [comment]
@arahayrabedian Already merged! I can't go around murdering collaborators to this repo, I'd be left alone to work on it then!

Thanks for your help!
