### ISSUE TITLE
Please select a license

### ISSUE THREAD

**Issue by arahayrabedian** [agile-leaf/50mm#12]
This should be an easy one once a decision is made, but since this is OSS you're going to want to pick a license. I'm not a lawyer, but [this makes scary](https://choosealicense.com/no-license/). I mean, it's not a lib or anything, but people using and contributing should know how things play out.

**Comment by theonejb** [comment]
Done. I selected MIT. If you feel something else is more appropriate for this, let me know.

**Comment by arahayrabedian** [comment]
nay, MIT is one of the most permissive :) :+1:
