### ISSUE TITLE
ordering filenames with spaces get looked up with %20 and fail

### ISSUE THREAD

**Issue by arahayrabedian** [agile-leaf/50mm#16]
Filenames specified (correctly) in an `ordering.yaml` file with spaces in them get the spaces encoded with `%20`, causing 50mm to think there is no file with that name in the bucket. This leads to that file's ordering entry being ignored (appears at end of album in bucket order).

No idea which part of the process this is happening in but will hunt it down.

**Comment by theonejb** [comment]
Probably the part where we use the `URL.ResolveReference` to convert URLs to a full bucket path, since that would encode _unsafe_ characters to their safer URL representation. Just a hunch.

**Comment by arahayrabedian** [comment]
i suspected the same, but didn't want to jump the gun. on the back burner but i'll get around to it eventually.
