### ISSUE TITLE
more generic resizing subsystem?

### ISSUE THREAD

**Issue by arahayrabedian** [agile-leaf/50mm#5]
Hi, just started playing with 50mm, I like what i'm seeing so far. I'd like to use something other than imgix for resizing. I've only taken a brief look at the source, but would you be open to a PR making the resizing subsystem generic enough to support other resizing backends? (e.g [picfit](https://github.com/thoas/picfit), though i've never used it.)

The major limitation here would be that the image processing service would have to be able to map the image URLs to the resized URLs, which I guess both imgix and picfit do. (otherwise 50mm needs it's own backing store, which is a bit of a leap here.)

**Comment by theonejb** [comment]
Definitely, any improvements to 50mm would be awesome!

I can see the appeal of other image sources, but I'd like to keep the codebase simple as well. Maybe we can discuss what approach to use before we actually start writing the code?

How does picfit work in terms of URL generation? For Imgix, you just get one base URL like `50mm.imgix.net` and then append your image name at the end of that.

So if you look at the imgix code right now, all it does is take the name of the image file (as it got from the AWS bucket) and just tacks it to the end of the base Imgix URL. Does picfit work in a similar way?

If so, maybe we could create a more generic image resize object in the code that works with services that work similarly? Services that just change the base URL of image objects?

**Comment by arahayrabedian** [comment]
so if you look at picfit's [redirect](https://github.com/thoas/picfit#redirect) method, my understanding is you'd do something like:

http://<your_picfit_domain>/redirect?url=<publicly_visible_photo_url>&w=200&h=0&op=resize

and your photo will be served, so the url generation method/format would simply have to change based on the service being used.

let me play with the code a little (this is my first foray in to golang) and i'll get back to discuss some structure/pick up advice.

**Comment by arahayrabedian** [comment]
solved by #9
